
name: BBB

on:
  workflow_dispatch:
  schedule:
     - cron: '0 7-23/2 * * *'
  watch:
    types: BBB
env:
  TZ: Asia/Shanghai
 
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BBB_ck: ${{ secrets.BBB_ck }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/adwktt.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.BBB_ck
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update
          npm install got
      - name: '运行 【BBB】'
        if: env.BBB_ck
        run: |
          cd ~/Scripts
          node BBB2.js
        env:
          BBB_ck: ${{ secrets.BBB_ck }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
