# File: .github/workflows/repo-sync.yml
name: 同步仓库
on:
  schedule:
    - cron: '15 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-jd_scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Pull image
        env:
          SOURCE_BRANCH: "master"
          DESTINATION_BRANCH: "jd"
          REPO_URL: "git@gitee.com:lxk0301/jd_scripts.git"
          SOURCE_IMAGE: "lxk0301/jd_scripts"
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
            cp -f syn.sh ~/syn.sh && chmod 755 ~/syn.sh && ~/syn.sh
            # cp -f auto_add_yml.sh ~/auto_add_yml.sh && chmod 755 ~/auto_add_yml.sh && bash ~/auto_add_yml.sh
